### Get the service document
http://localhost:4004/odata/v4/CatalogService

### Get service metadata document
http://localhost:4004/odata/v4/CatalogService/$metadata

### Get all employee data
http://localhost:4004/odata/v4/CatalogService/EmployeeSet

### Pagination Load data chunk by chunk
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$top=2&$skip=2

### Filtering Data - Where condition
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$filter=salaryAmount ge 1000000

### Count Records
http://localhost:4004/odata/v4/CatalogService/EmployeeSet/$count

### Get single record by key
http://localhost:4004/odata/v4/CatalogService/EmployeeSet/02BD2137-0890-1EEA-A6C2-BB55C197E7FB

### ASSOCIATIONS
### Get single PO
http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC2C052

### Get the PO and its Item together - Association
http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC2C052?$expand=Items

### V2 Adapter call
http://localhost:4004/v2/odata/v4/CatalogService/EmployeeSet
Authorization: Basic Manager: